import random

jokes = [
    "Why do programmers prefer dark mode? Less light, fewer bugs!", #Jokes generated by ChatGPT
    "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25!",
    "Why did the programmer quit his job? He didn't get arrays!",
    "Why do programmers hate nature? It has too many bugs!",
    "Why did the developer go broke? Because he used up all his cache!",
    "Why do programmers prefer iOS development? Because they love core dumps!",
    "Why did the database administrator leave his wife? She had too many constraints!",
    "Why don't programmers like nature? It has too many bugs!",
    "Why did the developer go broke? Because he used up all his cache!",
    "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25!",
    "Why did the developer go broke? Because he used up all his cache!",
    "Why did the database administrator leave his wife? She had too many constraints!",
    "Why do programmers prefer iOS development? Because they love core dumps!",
    "Why did the developer go broke? Because he used up all his cache!",
    "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25!",
    "Why did the developer go broke? Because he used up all his cache!",
    "Why do programmers prefer iOS development? Because they love core dumps!",
    ]

joke = random.choice(jokes)
print(joke)